[buildPlans.Iosevka]
family = "Iosevka"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.Iosevka.variants]
  inherits = "ss09"

    [buildPlans.Iosevka.variants.design]
    one = "base"
    three = "flat-top-serifless"
    zero = "oval-slashed"
    capital-q = "closed-swash"
    g = "single-storey-serifless"
    i = "serifed-semi-tailed"
    punctuation-dot = "square"
    braille-dot = "round"
    asterisk = "penta-low"
    paren = "large-contour"
    brace = "straight"
    guillemet = "curly"
    percent = "rings-continuous-slash"
    lig-neq = "slightly-slanted-dotted"

    [buildPlans.Iosevka.variants.italic]
    zero = "oval-slashed"
    capital-q = "closed-swash"
    f = "flat-hook-tailed"
    g = "single-storey-serifed"
    i = "serifed-semi-tailed"
    punctuation-dot = "round"
    asterisk = "penta-low"
    paren = "large-contour"
    brace = "straight"
    guillemet = "curly"
    percent = "rings-continuous-slash"

  [buildPlans.Iosevka.ligations]
  inherits = "dlig"

[buildPlans.Iosevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Iosevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Iosevka.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.Iosevka.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.Iosevka.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Iosevka.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.Iosevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Iosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Iosevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

